
version: "3"

services:
  app:
    build: .
    image: "citizensadvice/image-resizer"
    ports:
      - 4567:4567
    volumes:
      - .:/app
      - ./spec/fixtures/image_files:/app/spec/fixtures/image_files