name: Run linting

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af
        with:
          bundler-cache: true
      - run: bundle exec rubocop
